import { AbpHttpInterceptor, RefreshTokenService, AbpHttpConfigurationService } from 'abp-ng2-module';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import * as ApiServiceProxies from './service-proxies';
import { ZeroRefreshTokenService } from '@account/auth/zero-refresh-token.service';
import { ZeroTemplateHttpConfigurationService } from './zero-template-http-configuration.service';

@NgModule({
    providers: [
        ApiServiceProxies.PcsMainDashboardServiceProxy,
        ApiServiceProxies.MstAssessServiceProxy,
        ApiServiceProxies.CfgGenerateReportServiceProxy,
        ApiServiceProxies.PcsMainDashboardServiceProxy,
        ApiServiceProxies.MstCatalogServiceProxy,
        ApiServiceProxies.MstProcessTypeServiceProxy,
        ApiServiceProxies.PrcContractLineServiceProxy,
        ApiServiceProxies.PrcContractHeaderServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.PrcContractTemplateServiceProxy,
        ApiServiceProxies.MstNationServiceProxy,
        ApiServiceProxies.MstProvinceServiceProxy,
        ApiServiceProxies.MstDistrictServiceProxy,
        ApiServiceProxies.MstProjectServiceProxy,
        ApiServiceProxies.MstQuotaExpenseServiceProxy,
        ApiServiceProxies.MstGlCodeCombinationServiceProxy,
        ApiServiceProxies.MstCurrencyServiceProxy,
        ApiServiceProxies.MstGlExchangeRateServiceProxy,
        ApiServiceProxies.RequestApprovalServiceProxy,
        ApiServiceProxies.DigitalInvoiceServiceProxy,
        ApiServiceProxies.MstSupplierRequestServiceProxy,
        ApiServiceProxies.RequestApprovalTreeServiceProxy,
        ApiServiceProxies.CommonGeneralCacheServiceProxy,
        ApiServiceProxies.UrUserRequestManagementServiceProxy,
        ApiServiceProxies.UrBuyFromCatalogRequestServiceProxy,
        ApiServiceProxies.MstPeriodServiceProxy,
        ApiServiceProxies.MstPurchasePurposeServiceProxy,
        ApiServiceProxies.MstCategoriesServiceProxy,
        ApiServiceProxies.MstLineTypeServiceProxy,
        ApiServiceProxies.MstLocationsServiceProxy,
        ApiServiceProxies.MstOrganizationsServiceProxy,
        ApiServiceProxies.PurchaseRequestServiceProxy,
        ApiServiceProxies.MstInventoryGroupServiceProxy,
        ApiServiceProxies.MstInventoryItemsServiceProxy,
        ApiServiceProxies.MstCancelReasonServiceProxy,
        ApiServiceProxies.MstContractTemplateServiceProxy,
        ApiServiceProxies.MstProductGroupServiceProxy,
        ApiServiceProxies.MstDocumentServiceProxy,
        ApiServiceProxies.RcvShipmentHeadersServiceProxy,
        ApiServiceProxies.RcvRoutingHeadersServiceProxy,
        ApiServiceProxies.RcvReceiptNoteHeadersServiceProxy,
        ApiServiceProxies.MstInventoryItemSubInventoriesServiceProxy,
        ApiServiceProxies.MstInventoryCodeConfigServiceProxy,
        ApiServiceProxies.InvoiceAdjustedServiceProxy,

        ApiServiceProxies.AuditLogServiceProxy,
        ApiServiceProxies.CachingServiceProxy,
        ApiServiceProxies.ChatServiceProxy,
        ApiServiceProxies.CommonLookupServiceProxy,
        ApiServiceProxies.EditionServiceProxy,
        ApiServiceProxies.FriendshipServiceProxy,
        ApiServiceProxies.HostSettingsServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.LanguageServiceProxy,
        ApiServiceProxies.NotificationServiceProxy,
        ApiServiceProxies.OrganizationUnitServiceProxy,
        ApiServiceProxies.PermissionServiceProxy,
        ApiServiceProxies.ProfileServiceProxy,
        ApiServiceProxies.RoleServiceProxy,
        ApiServiceProxies.SessionServiceProxy,
        ApiServiceProxies.TenantServiceProxy,
        ApiServiceProxies.TenantDashboardServiceProxy,
        ApiServiceProxies.TenantSettingsServiceProxy,
        ApiServiceProxies.TimingServiceProxy,
        ApiServiceProxies.UserServiceProxy,
        ApiServiceProxies.UserLinkServiceProxy,
        ApiServiceProxies.UserLoginServiceProxy,
        ApiServiceProxies.WebLogServiceProxy,
        ApiServiceProxies.AccountServiceProxy,
        ApiServiceProxies.TokenAuthServiceProxy,
        ApiServiceProxies.TenantRegistrationServiceProxy,
        ApiServiceProxies.HostDashboardServiceProxy,
        ApiServiceProxies.PaymentServiceProxy,
        ApiServiceProxies.DemoUiComponentsServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.SubscriptionServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.UiCustomizationSettingsServiceProxy,
        ApiServiceProxies.PayPalPaymentServiceProxy,
        ApiServiceProxies.StripePaymentServiceProxy,
        ApiServiceProxies.DashboardCustomizationServiceProxy,
        ApiServiceProxies.WebhookEventServiceProxy,
        ApiServiceProxies.WebhookSubscriptionServiceProxy,
        ApiServiceProxies.WebhookSendAttemptServiceProxy,
        ApiServiceProxies.UserDelegationServiceProxy,
        ApiServiceProxies.DynamicPropertyServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyDefinitionServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyServiceProxy,
        ApiServiceProxies.DynamicPropertyValueServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyValueServiceProxy,
        ApiServiceProxies.TwitterServiceProxy,
        ApiServiceProxies.MstCurrencyServiceProxy,
        ApiServiceProxies.MstUnitOfMeasureServiceProxy,
        ApiServiceProxies.MstInventoryItemsServiceProxy,
        ApiServiceProxies.MstSupplierServiceProxy,
        ApiServiceProxies.MstApprovalTreeServiceProxy,
        ApiServiceProxies.PaymentHeadersServiceProxy,
        ApiServiceProxies.InvoicesServiceProxy,
        ApiServiceProxies.MstInventoryItemPriceServiceProxy,
        ApiServiceProxies.PurchaseOrdersServiceProxy,
        ApiServiceProxies.PersonnelServiceProxy,
        ApiServiceProxies.MstHrOrgStructureServiceProxy,
        ApiServiceProxies.PrepaymentServiceProxy,
        ApiServiceProxies.BmsMstSegment1ServiceProxy,
        ApiServiceProxies.BmsMstSegment2ServiceProxy,
        ApiServiceProxies.BmsMstSegment3ServiceProxy,
        ApiServiceProxies.BmsMstSegment4ServiceProxy,
        ApiServiceProxies.BmsMstSegment5ServiceProxy,
        ApiServiceProxies.BmsPeriodVersionServiceProxy,
        ApiServiceProxies.BmsMstPeriodServiceProxy,
        ApiServiceProxies.SegmentExcelServiceProxy,
        ApiServiceProxies.BmsMstPairingSegmentServiceProxy,
        ApiServiceProxies.BmsMstSegment1TypeCostServiceProxy,
        ApiServiceProxies.BmsMstSegment2ProjectTypeServiceProxy,
        ApiServiceProxies.BmsMstSegment4GroupServiceProxy,
        ApiServiceProxies.ExchangeRateMasterServiceProxy,
        ApiServiceProxies.ProjectCodeServiceProxy,
        ApiServiceProxies.BudgetTransferServiceProxy,
        ApiServiceProxies.BmsBudgetUserControlServiceProxy,
        ApiServiceProxies.BmsBudgetPlanReviewServiceProxy,
        { provide: RefreshTokenService, useClass: ZeroRefreshTokenService },
        { provide: AbpHttpConfigurationService, useClass: ZeroTemplateHttpConfigurationService },
        { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true },
    ],
})
export class ServiceProxyModule {}
