export const TABS = {
    // Admin
    ADMIN_ORGANIZATION_UNITS: 'ADMIN_ORGANIZATION_UNITS',
    ADMIN_USERS: 'ADMIN_USERS',
    ADMIN_ROLES: 'ADMIN_ROLES',
    ADMIN_AUDIT_LOGS: 'ADMIN_AUDIT_LOGS',
    ADMIN_LANGUAGE: 'ADMIN_LANGUAGE',
    ADMIN_UI_CUSTOMIZATION: 'ADMIN_UI_CUSTOMIZATION',
    ADMIN_HOST_SETTINGS: 'ADMIN_HOST_SETTINGS',
    ADMIN_TENANT_SETTINGS: 'ADMIN_TENANT_SETTINGS',

    AP_SPP_CHECK_INVOICE: 'AP_SPP_CHECK_INVOICE',
    GET_DATA_MODAL: 'GET_DATA_MODAL',

    /* Master */
    MASTER_TEST: 'MASTER_TEST',
    MASTER_PERIOD: 'MASTER_PERIOD',
    MASTER_PURCHASE_PURPOSE: 'MASTER_PURCHASE_PURPOSE',
    MASTER_CURRENCY: 'MASTER_CURRENCY',
    MASTER_CATALOG_PRICE_MANAGEMENT: 'MASTER_CATALOG_PRICE_MANAGEMENT',
    MASTER_BUY_PURPOSE: 'MASTER_BUY_PURPOSE',
    MASTER_CURRENCY_DATA: 'MASTER_CURRENCY_DATA',
    MASTER_BUDGET_CODE: 'MASTER_BUDGET_CODE',
    MASTER_PROJECT: 'MASTER_PROJECT',
    MASTER_QUOTA_EXPENSE: 'MASTER_QUOTA_EXPENSE',
    MASTER_PRODUCT_GROUP: 'MASTER_PRODUCT_GROUP',
    MASTER_LIST_OF_DOCUMENT: 'MASTER_LIST_OF_DOCUMENT',
    MASTER_CATALOG: 'MASTER_CATALOG',
    MASTER_INVENTORY_CODE_CONFIG: 'MASTER_INVENTORY_CODE_CONFIG',

    //pr
    PURCHASE_REQUEST: 'PURCHASE_REQUEST',
    CREATE_OR_EDIT_PURCHASE_REQUEST: 'CREATE_OR_EDIT_PURCHASE_REQUEST',

    //po
    PURCHASE_ORDERS: 'PURCHASE_ORDERS',
    CREATE_OR_EDIT_PURCHASE_ORDERS: 'CREATE_OR_EDIT_PURCHASE_ORDERS',
    AUTO_CREATE_PURCHASE_ORDERS: 'AUTO_CREATE_PURCHASE_ORDERS',
    AUTO_CREATE_PURCHASE_ORDERS_FROM_CONTRACT: 'AUTO_CREATE_PURCHASE_ORDERS_FROM_CONTRACT',

    MASTER_UNIT_OF_MEASURE: 'MASTER_UNIT_OF_MEASURE',
    MASTER_SUPPLIER: 'MASTER_SUPPLIER',
    MASTER_SUPPLIER_REQUEST: 'MASTER_SUPPLIER_REQUEST',
    MASTER_INVENTORY_ITEM: 'MASTER_INVENTORY_ITEM',
    MASTER_APPROVAL_TREE: 'MASTER_APPROVAL_TREE',
    MASTER_INVENTORY_GROUP: 'MASTER_INVENTORY_GROUP',
    MASTER_INVENTORY_GROUP_MODAL: 'MASTER_INVENTORY_GROUP_MODAL',
    MASTER_HR_ORG_STRUCTURE: 'MASTER_HR_ORG_STRUCTURE',
    MASTER_PRODUCT_INVENTORY_ITEM: 'MASTER_PRODUCT_INVENTORY_ITEM',
    MASTER_PRICE_INVENTORY_ITEM: 'MASTER_PRICE_INVENTORY_ITEM',
    FRAMEWORK_CONTRACT_CATALOG: 'FRAMEWORK_CONTRACT_CATALOG',
    MST_CANCEL_REASON: 'MST_CANCEL_REASON',
    MASTER_ASSESS: 'MASTER_ASSESS',
    MASTER_ASSESS_GROUP: 'MASTER_ASSESS_GROUP',

    /* User Request */
    UR_BUY_REQUEST_FROM_CATALOG: 'UR_BUY_REQUEST_FROM_CATALOG',
    UR_REQUEST: 'UR_REQUEST',
    UR_CREATE_USER_REQUEST: 'UR_CREATE_USER_REQUEST',
    UR_AUTO_CREATE_PR: 'UR_AUTO_CREATE_PR',

    GOODS_RECEIPT: 'GOODS_RECEIPT',
    CREATE_OR_EDIT_GOODS_RECEIPT: 'CREATE_OR_EDIT_GOODS_RECEIPT',
    CREATE_OR_EDIT_GR_FROM_RECEIPT_NOTES: 'CREATE_OR_EDIT_GR_FROM_RECEIPT_NOTES',
    RETURN_GOODS_RECEIPT: 'RETURN_GOODS_RECEIPT',
    RETURN_GOODS_RECEIPT_LIST: 'RETURN_GOODS_RECEIPT_LIST',

    RECEIPT_NOTES: 'RECEIPT_NOTES',
    CREATE_OR_EDIT_RECEIPT_NOTES: 'CREATE_OR_EDIT_RECEIPT_NOTES',
    VIEW_GOODS_RECEIPT: 'VIEW_GOODS_RECEIPT',
    VIEW_RECEIPT_NOTE: 'VIEW_RECEIPT_NOTE',

    FRAMEWORK_CONTRACT_MANAGEMENT: 'FRAMEWORK_CONTRACT_MANAGEMENT',

    /* Approve Requests  */
    APPROVE_REQUEST: 'APPROVE_REQUEST',

    /* Sys Config */
    SYS_SYSTEM_CONFIG: 'SYS_SYSTEM_CONFIG',

    /*Payment Request*/
    PAYMENT_REQUEST: 'PAYMENT_REQUEST',
    CREATE_OR_EDIT_PAYMENT_REQUEST: 'CREATE_OR_EDIT_PAYMENT_REQUEST',
    INVOICE: 'INVOICE',
    INVOCIE_ADJUSTED: 'INVOCIE_ADJUSTED',
    CREATE_OR_EDIT_INVOCIE_ADJUSTED: 'CREATE_OR_EDIT_INVOCIE_ADJUSTED',
    DIGITAL_INVOICE: 'DIGITAL_INVOICE',
    DIGITAL_INVOICE_DETAIL: 'DIGITAL_INVOICE_DETAIL',
    COMPARE_INVOICE: 'COMPARE_INVOICE',
    PAYMENT_ADVANCE: 'PAYMENT_ADVANCE',
    PAYMENT_REQUEST_FROM_SUPPLIERS: 'PAYMENT_REQUEST_FROM_SUPPLIERS',
    BMS_MST_SEGMENT1: 'BMS_MST_SEGMENT1',
    BMS_MST_SEGMENT2: 'BMS_MST_SEGMENT2',
    BMS_MST_SEGMENT3: 'BMS_MST_SEGMENT3',
    BMS_MST_SEGMENT4: 'BMS_MST_SEGMENT4',
    BMS_MST_SEGMENT5: 'BMS_MST_SEGMENT5',
    BMS_MST_PERIOD: 'BMS_MST_PERIOD',
    BMS_MST_PAIRING_SEGMENT: 'BMS_MST_PAIRING_SEGMENT',
    BMS_MST_SEGMENT1_TYPE_COST: 'BMS_MST_SEGMENT1_TYPE_COST',
    BMS_MST_SEGMENT2_PROJECT_TYPE: 'BMS_MST_SEGMENT2_PROJECT_TYPE',
    BMS_MST_SEGMENT4_GROUP: 'BMS_MST_SEGMENT4_GROUP',
    BMS_MST_EXCHANGE_RATE: 'BMS_MST_EXCHANGE_RATE',
    BMS_MST_PROJECT_CODE: 'BMS_MST_PROJECT_CODE',
    BMS_USER_BUDGET_CONTROL: 'BMS_USER_BUDGET_CONTROL',
    BMS_BUDGET_TRANSFER: 'BMS_BUDGET_TRANSFER',
    BMS_BUDGET_REVIEW: 'BMS_BUDGET_REVIEW',
    BMS_BUDGET_PLAN_REVIEW: 'BMS_BUDGET_PLAN_REVIEW',
    /* Dashboard */
    MAIN_DASHBOARD: 'MAIN_DASHBOARD',


    // sourcing
    SOURCING_LIST : 'SOURCING_LIST',

};
